config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'lots#index'
   resources :lots
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lot.rb
class Lot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController

     def index
      @lots = Lot.all
      end

    def new
      @lot = Lot.new
    end
   

      def create
        @lot = Lot.create(lot_params)
        if @lot.valid?
           redirect_to root_path
        else
          render :new, status: :unprocessable_entity
        end
      end

      private

      def lot_params
        params.require(:lot).permit(:name, :address, :description)
      end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quanteq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    

                <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">Quanteq</a>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <%= link_to 'New lot', new_lot_path, class: 'nav-link' %>
                </li>
              </ul>
            </div>
          </nav>

      <%= yield %>
      
  </body>
</html>

app/views/lots/index.html.erb
<% @lots.each do |lot| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= lot.name %></h1>
    <i><%= lot.address %></i><br /><br />
    <p><%= lot.description %></p><br />
  </div>

  <hr />
<% end %>

app/views/lots/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new lot</h1>
  <%= simple_form_for @lot, url: lots_path do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/static_pages/index.html.erb
<h1 style="color:red;">Build my first app</h1>
<h2 style="color:blue;">Baby step into fullstack.</h2>